
GET http://localhost:9500/api/v1/health/live

###

GET http://localhost:9500/api/v1/health/ready



###
POST http://localhost:9500/api/v1/user
Content-Type: application/json 

{
  "username": "helloworld",
  "email": "hello@world.id",
  "password": "password123"
}
###

POST http://localhost:9500/api/v1/user/login
Content-Type: application/json 

{
  "email": "hello@world.id",
  "password": "password123"
}
###
